# Generated by Django 4.0.1 on 2022-01-06 05:40

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='due_date',
            field=models.DateField(default=quiz.models.get_deadline, verbose_name='Срок выполнения'),
        ),
    ]
