# Generated by Django 4.0 on 2022-01-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Группа')),
                ('slug', models.SlugField(help_text='Адрес страницы', unique=True, verbose_name='ЧПУ')),
                ('description', models.TextField(blank=True, help_text='Необязательно к заполнению', verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('students', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_joined', to='auth.user', verbose_name='Студенты')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Адрес страницы', max_length=200, unique=True, verbose_name='ЧПУ')),
                ('description', models.TextField(blank=True, help_text='Необязательно к заполнению', verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses_joined', to='classroom.group', verbose_name='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_created', to='auth.user', verbose_name='Автор курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['title'],
            },
        ),
    ]
