# Generated by Django 4.0 on 2022-01-04 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='group',
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='courses_joined', to='classroom.Group', verbose_name=''),
        ),
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='group_joined', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
    ]
