# Generated by Django 4.0.1 on 2022-01-06 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0006_content_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='group_joined', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
    ]
