# Generated by Django 4.0.1 on 2022-01-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_group_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='group',
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='courses_joined', to='classroom.group', verbose_name='Группа'),
        ),
    ]
