# Generated by Django 4.0.1 on 2022-01-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_remove_course_group_course_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_joined', to='classroom.group', verbose_name='Группа'),
        ),
    ]
